const BASE_RETAILERS = [
    { id: 1, name: "Hamilton's Jewelry", platform: "Custom", image: "https://stargems.com/assets/img/Websites/HJ.webp", url: "https://hamiltonjewelersonline.com/" },
    { id: 2, name: "Rare Gem Studio", platform: "Custom", image: "https://stargems.com/assets/img/Websites/RGS.webp", url: "https://raregemstudio.com/" },
    { id: 3, name: "Barnards Fine Jewelry", platform: "Custom", image: "https://stargems.com/assets/img/Websites/BFJ.webp", url: "https://barnardsjewelry.com/" },
    { id: 4, name: "Baggett's Jewelry", platform: "Custom", image: "https://stargems.com/assets/img/Websites/BAG.webp", url: "https://www.baggettsjewelry.com/" },
    { id: 5, name: "Alabama Family Optometry", platform: "Custom", image: "https://stargems.com/assets/img/Websites/AFO.webp", url: "https://afoptometry.com/" },
    { id: 6, name: "Showcase Jewelers - Hays", platform: "Custom", image: "https://stargems.com/assets/img/Websites/HAYS.webp", url: "https://showcasehays.com/" },
    { id: 7, name: "Marks Jewelry Co.", platform: "Custom", image: "https://stargems.com/assets/img/Websites/MARKS.webp", url: "https://marksjewelryco.com/" },
    { id: 8, name: "Lovette Jewelers", platform: "Custom", image: "https://stargems.com/assets/img/Websites/LOVETTE.webp", url: "https://lovettejewelers.com/" },
    { id: 9, name: "KeepSakes Jewelry", platform: "Custom", image: "https://stargems.com/assets/img/Websites/KSJ.webp", url: "https://keepsakesjewelry.com/" },
    { id: 10, name: "Jewelers On Main", platform: "Custom", image: "https://stargems.com/assets/img/Websites/JOM.webp", url: "https://jewelersonmain.com/" },
    { id: 11, name: "Morande Jewelers", platform: "Custom", image: "https://stargems.com/assets/img/Websites/MORA.webp", url: "https://morandejewelers.com/" },
    { id: 12, name: "Fountain City Jewelers", platform: "Custom", image: "https://stargems.com/assets/img/Websites/FCJ.webp", url: "https://fountaincityjewelers.com/" },
    { id: 13, name: "Concierge Jewelry Repair", platform: "Custom", image: "https://stargems.com/assets/img/Websites/CONC.webp", url: "https://conciergejewelryrepair.com/" },
    { id: 14, name: "Zembar Jewelers", platform: "Custom", image: "https://stargems.com/assets/img/Websites/ZEMB.webp", url: "https://www.zembarjeweler.com/" },
    { id: 15, name: "Steves Custom Jewelers", platform: "Custom", image: "https://stargems.com/assets/img/Websites/SCJ.webp", url: "https://stevescustomjewelers.com/" },
    { id: 16, name: "TPM&F", platform: "Custom", image: "https://stargems.com/assets/img/Websites/TPM.webp", url: "https://spetpmf.com/" },
    { id: 17, name: "Stephens Fine Jewelry", platform: "Custom", image: "https://stargems.com/assets/img/Websites/SFJ.webp", url: "https://stephensfinejewelryoh.com/" },
    { id: 18, name: "Signature Diamonds", platform: "Custom", image: "https://stargems.com/assets/img/Websites/SDG.webp", url: "https://signaturediamondsknoxville.com/" },
    { id: 19, name: "Showcase Jewelers - Salina", platform: "Custom", image: "https://stargems.com/assets/img/Websites/SALINA.webp", url: "https://showcasejewelers.net/" },
    { id: 20, name: "Quality Jewelers", platform: "Custom", image: "https://stargems.com/assets/img/Websites/QJ.webp", url: "https://qualityjewelers.com/" },
    { id: 21, name: "Marshall's Jewelers", platform: "Custom", image: "https://stargems.com/assets/img/Websites/MAJ.webp", url: "https://www.marshallsjewelersonline.com/" },
    { id: 22, name: "Dylan Rings", platform: "Custom", image: "https://stargems.com/assets/img/Websites/DR.webp", url: "https://www.dylanrings.com/" },
    { id: 23, name: "Talles Diamonds and Gold", platform: "Custom", image: "https://stargems.com/assets/img/Websites/TDG.webp", url: "https://tallesdiamonds.com/" },
    { id: 24, name: "Jefferson Estate Jewelers", platform: "Custom", image: "https://stargems.com/assets/img/Websites/JEFF.webp", url: "https://jeffersonestatejewelers.com/" },
    { id: 25, name: "Henry's Jewelers", platform: "Custom", image: "https://stargems.com/assets/img/Websites/HENRYS.webp", url: "https://www.henrys-jewelers.com/" },
    { id: 26, name: "Ellington Jewelers, Inc", platform: "Custom", image: "https://stargems.com/assets/img/Websites/EJ.webp", url: "https://ellingtonjewelers.com/" },
    { id: 27, name: "Lowery Jewelers", platform: "Custom", image: "https://stargems.com/assets/img/Websites/LJ.webp", url: "https://loweryjewelers.com/" },
    { id: 28, name: "Hinz Jewelers", platform: "Custom", image: "https://stargems.com/assets/img/Websites/HINZ.webp", url: "https://hinzjewelers.com/" },
    { id: 29, name: "Gregory Jewelers", platform: "Custom", image: "https://stargems.com/assets/img/Websites/GJM.webp", url: "https://gregoryjewelersofmorganton.com/" },
    { id: 30, name: "Gemco International", platform: "Custom", image: "https://stargems.com/assets/img/Websites/GEMCO.webp", url: "https://gemcodiamond.com/" },
    { id: 31, name: "Gayle's Jewelers", platform: "Custom", image: "https://stargems.com/assets/img/Websites/GJ.webp", url: "https://www.gaylesjewelers.com/" },
    { id: 32, name: "Fancy That Jewelry in Stockbridge, GA", platform: "Custom", image: "https://stargems.com/assets/img/Websites/FT.webp", url: "http://afancythatjewelry.com/" },
    { id: 33, name: "Ed White Jewelers", platform: "Custom", image: "https://stargems.com/assets/img/Websites/EWJ.webp", url: "http://edwhitejewelers.com/" },
    { id: 34, name: "Jewelmasters", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/Jewel-Masters.webp", url: "http://jewelmastersonline.com/" },
    { id: 35, name: "M & M Jewelers", platform: "Custom", image: "https://stargems.com/assets/img/Websites/MMJ.webp", url: "http://mmjewelersbirmingham.com/" },
    { id: 36, name: "A. T. Thomas Jewelers", platform: "Custom", image: "https://stargems.com/assets/img/Websites/ATT.webp", url: "http://atthomasjewelers.com/" },
    { id: 37, name: "Bowman Jewelers", platform: "Custom", image: "https://stargems.com/assets/img/Websites/BJJ.webp", url: "http://bowmanjewelers.com/" },
    { id: 38, name: "Diamond Depot", platform: "Custom", image: "https://stargems.com/assets/img/Websites/DDA.webp", url: "http://oxforddiamonddepot.com/" },
    { id: 39, name: "Pearson's Jewelers", platform: "Custom", image: "https://stargems.com/assets/img/Websites/PEAR.webp", url: "http://pearsonsjewelersca.com/" },
    { id: 40, name: "Kent island Jewelry LLC", platform: "Custom", image: "https://stargems.com/assets/img/Websites/KENT.webp", url: "http://kentislandjewelry.com/" },
    { id: 41, name: "DeAngelis Jewelers", platform: "Custom", image: "https://stargems.com/assets/img/Websites/DEAN.webp", url: "http://deangelisjewelers.com/" },
    { id: 42, name: "Midtown Jewelers", platform: "Custom", image: "https://stargems.com/assets/img/Websites/MIDT.webp", url: "http://midtownjewelersinc.com/" },
    { id: 43, name: "TJ's Fine Jewelry", platform: "Custom", image: "https://stargems.com/assets/img/Websites/TJSFJ.webp", url: "http://tjsfinejewelry.com/" },
    { id: 44, name: "Pettit Jewelers", platform: "NOP", image: "https://stargems.com/assets/img/Websites/Pettit-Jewelers.jpeg", url: "http://pettitjewelers.com/" },
    { id: 45, name: "Avalon Park Jewelers", platform: "NOP", image: "https://stargems.com/assets/img/Websites/Avalon-Park-Jewelers.jpeg", url: "http://avalonparkjewelers.com/" },
    { id: 46, name: "King Diamonds", platform: "NOP", image: "https://stargems.com/assets/img/Websites/King-Diamonds.jpeg", url: "http://kingdiamondsonline.com/" },
    { id: 47, name: "Lisy Custom Jewelers", platform: "NOP", image: "https://stargems.com/assets/img/Websites/LISY.webp", url: "https://lisyjewelers.com/" },
    { id: 48, name: "Smoky Mountain Coin and Jewelry", platform: "NOP", image: "https://stargems.com/assets/img/Websites/smoky-mountain.jpeg", url: "http://smokymountaincoinandjewelry.com/" },
    { id: 49, name: "Bryant Gem", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/Bryants-Gems.webp", url: "http://bryantgems.com/" },
    { id: 50, name: "Stokes Jewelry", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/Stokes-Jewelry.webp", url: "http://stokesjewelry.com/" },
    { id: 51, name: "Helmut The Jeweler", platform: "Custom", image: "https://stargems.com/assets/img/Websites/HELMUT.webp", url: "http://helmutjewelry.com/" },
    { id: 52, name: "West Essex Jewelers", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/WEST.webp", url: "https://westessexjewelers.net/" },
    { id: 53, name: "Alabama Wholesale Diamonds", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/Alabama-wholesale-Diamonds.webp", url: "http://alabamawholesalediamonds.com/" },
    { id: 54, name: "Precious Fine Jewelers", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/PRECIOUS.webp", url: "http://preciousfinejewelers.com/" },
    { id: 55, name: "SHR Precious Metals, Inc.", platform: "Custom", image: "https://stargems.com/assets/img/Websites/SHR.webp", url: "http://www.shrefining.com/" },
    { id: 56, name: "Bergey Jewelry", platform: "Custom", image: "https://stargems.com/assets/img/Websites/Bergey.webp", url: "http://www.bergeyjewelry.com/" },
    { id: 57, name: "Julie's Jewels & Gifts", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/Julies-Jewels-and-Gifts-SC.webp", url: "http://juliesjewelsandgifts.com/" },
    { id: 58, name: "Alexander’s of Atlanta", platform: "Custom", image: "https://stargems.com/assets/img/Websites/AOA.webp", url: "http://alexandersofatlanta.com/" },
    { id: 59, name: "Albrecht Jewelry", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/Albrecht-Jewelry.webp", url: "http://www.albrechtjewelry.com/" },
    { id: 60, name: "ASBA USA", platform: "Custom", image: "https://stargems.com/assets/img/Websites/ASBA.webp", url: "http://www.asbausa.com/" },
    { id: 61, name: "Brummitt Jewelry Design Studio", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/Brummitt-Jewelry-Studio.webp", url: "http://www.brummittjewelrystudio.com/" },
    { id: 62, name: "Brilliant Gem Buttons", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/BGB.webp", url: "https://brilliantgembuttons.com/" },
    { id: 63, name: "Dublin Village Jewelers", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/Dublin-Village-Jewelers.webp", url: "http://www.dublinvillagejewelers.com/" },
    { id: 64, name: "Eduardo Accostupa Jewelry Designer", platform: "Wordpress", image: "https://stargems.com/assets/img/Websites/EDUA.webp", url: "http://www.eduardoaccostupa.com/" },
    { id: 65, name: "Coats Jewelers", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/Coats-Jewelers.webp", url: "http://coatsjewelers.com/" },
    { id: 66, name: "Humphreys & Sons", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/HUMP.webp", url: "https://humphreysandson.com/" },
    { id: 67, name: "Clayton Jewelers", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/Clayton-jewelers.webp", url: "http://claytonjewelers.net/" },
    { id: 68, name: "Famulare Jewelers", platform: "Others", image: "https://stargems.com/assets/img/Websites/Famulare-Jewelers.webp", url: "http://www.famularejewelers.com/" },
    { id: 69, name: "J. David Jewelry", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/J-DAVID-JEWELRY.webp", url: "http://jdavidjewelry.com/" },
    { id: 70, name: "Stevens Creations LLC", platform: "Custom", image: "https://stargems.com/assets/img/Websites/stevenscreationsllc.webp", url: "http://stevencreationsllc.com/" },
    { id: 71, name: "Treasures Old & New", platform: "Custom", image: "https://stargems.com/assets/img/Websites/TON.webp", url: "http://treasureson.com/" },
    { id: 72, name: "Baraka Gems", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/Baraka-Gems.webp", url: "http://barakagems.com/" },
    { id: 73, name: "Wright's Jewelry", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/Wrights-Jewelry.webp", url: "http://www.wrightsjewelrystore.com/" },
    { id: 74, name: "Skyline Gems", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/Skyline-G.webp", url: "http://skylinegems.com/" },
    { id: 75, name: "Brillante Jeweler", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/Brillante-and-Co.webp", url: "http://www.brillantejeweler.com/" },
    { id: 76, name: "Wendels Jewelers", platform: "Custom", image: "https://stargems.com/assets/img/Websites/wendelsjewelers.webp", url: "http://wendelsjewelers.com/" },
    { id: 77, name: "The Jewelry Guy", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/TJG.webp", url: "https://thejewelryguy.com/" },
    { id: 78, name: "Gwens Fine Jewelers", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/Gwens-Fine-Jewelers.webp", url: "http://www.gwensfinejewelers.com/" },
    { id: 79, name: "Jewelry Savers", platform: "Wordpress", image: "https://stargems.com/assets/img/Websites/ewelry-Savers-Inc.webp", url: "http://www.jewelrysavers.com/" },
    { id: 80, name: "Infinger's Jewelry", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/Infingers-Jewelry.webp", url: "https://www.infingers.com/" },
    { id: 81, name: "Leo Hamel Fine Jewelers", platform: "Wordpress", image: "https://stargems.com/assets/img/Websites/Leo-Hamel-Fine-Jewelers.webp", url: "https://www.leohamel.com/" },
    { id: 82, name: "Richardson Jewelers Marquette", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/Richardson-Jewelers-MQT.webp", url: "https://richardsonjewelersmqt.com/" },
    { id: 83, name: "K. Zander Jewelry", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/K-Zander-Jewelry.webp", url: "https://kzanderjewelry.com/" },
    { id: 84, name: "Sparkles Jewelry", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/Sparkles-Jewelry.webp", url: "http://www.sparklesjewelrymi.com/" },
    { id: 85, name: "David Porter Jewelry", platform: "Custom", image: "https://stargems.com/assets/img/Websites/DPJ.webp", url: "https://www.davidporterjewelry.com/" },
    { id: 86, name: "Hustedt Jewelers", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/Hustedt-Jewelers.webp", url: "http://hustedtjewelers.com/" },
    { id: 87, name: "Cooper Fine Jewelers", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/COOP.webp", url: "http://cooperfinejewelers.com/" },
    { id: 88, name: "Carolina Diamond Buyer", platform: "Wordpress", image: "https://stargems.com/assets/img/Websites/Carolina-Diamond-Buyer.webp", url: "https://carolinadiamondbuyer.com/" },
    { id: 89, name: "You Design We Create", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/AJs-jewelry.webp", url: "http://youdesignwecreate.com/" },
    { id: 90, name: "W.P. Shelton Jewelers", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/WP-Shelton-Jewelers.webp", url: "http://www.wpsheltonjewelers.com/" },
    { id: 91, name: "Borthwick Jewelry", platform: "Custom", image: "https://stargems.com/assets/img/Websites/BJC.webp", url: "http://http//borthwickjewelry.com" },
    { id: 92, name: "Wolf Jewelry and Watches", platform: "Wordpress", image: "https://stargems.com/assets/img/Websites/Wolf-Jewelry.webp", url: "http://thewolfjewelry.com/" },
    { id: 93, name: "Rocky’s Diamond Gallery", platform: "Custom", image: "https://stargems.com/assets/img/Websites/ROCK.webp", url: "http://www.rockysdiamonds.com/" },
    { id: 94, name: "Mansi Jewelry", platform: "Shopify", image: "https://stargems.com/assets/img/Websites/Mansi-Jewelry.webp", url: "http://mansijewelry.com/" },
    { id: 95, name: "Dale Robertson Jewelry", platform: "Custom", image: "https://stargems.com/assets/img/Websites/DALE.webp", url: "https://dalerobertsonjewelry.com/" }
];
