tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "outline-variant": "#c3c7cf",
                "tertiary-container": "#627691",
                "primary": "#3b5e84",
                "error-container": "#ffdad6",
                "tertiary-fixed-dim": "#b4c8e6",
                "surface-container-lowest": "#ffffff",
                "primary-fixed-dim": "#a6c9f5",
                "surface-bright": "#f9f9f9",
                "surface-variant": "#e2e2e2",
                "error": "#ba1a1a",
                "inverse-primary": "#a6c9f5",
                "outline": "#73777f",
                "surface": "#f9f9f9",
                "on-tertiary-container": "#fdfcff",
                "on-error": "#ffffff",
                "on-surface-variant": "#42474e",
                "background": "#f9f9f9",
                "on-surface": "#1a1c1c",
                "on-tertiary": "#ffffff",
                "on-secondary": "#ffffff",
                "surface-dim": "#dadada",
                "on-background": "#1a1c1c",
                "tertiary": "#4a5d77",
                "surface-container": "#eeeeee",
                "inverse-on-surface": "#f1f1f1",
                "on-primary-fixed-variant": "#23496e",
                "on-error-container": "#93000a",
                "on-secondary-container": "#415d7f",
                "tertiary-fixed": "#d3e4ff",
                "inverse-surface": "#2f3131",
                "secondary-container": "#b9d7fe",
                "primary-container": "#54779e",
                "secondary-fixed": "#d1e4ff",
                "secondary": "#446082",
                "on-secondary-fixed-variant": "#2b4969",
                "surface-tint": "#3d6187",
                "on-primary-container": "#fdfcff",
                "primary-fixed": "#d1e4ff",
                "surface-container-high": "#e8e8e8",
                "secondary-fixed-dim": "#abc9ef",
                "on-tertiary-fixed-variant": "#354861",
                "surface-container-low": "#f3f3f3",
                "on-secondary-fixed": "#001d36",
                "on-tertiary-fixed": "#061c33",
                "on-primary-fixed": "#001d35",
                "on-primary": "#ffffff",
                "surface-container-highest": "#e2e2e2"
            },
            fontFamily: {
                "headline": ["Noto Serif", "Cormorant Garamond", "serif"],
                "body": ["Inter", "IBM Plex Sans", "sans-serif"],
                "label": ["Inter", "sans-serif"],
                "serif": ["Cormorant Garamond", "serif"],
                "sans": ["IBM Plex Sans", "sans-serif"]
            },
            borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" }
        }
    }
};
